services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"